[package]
name = "ps-pint16"
version = "0.1.0-4"
edition = "2021"
description = "Packs integers into a u16 via variable precision"
license = "GPL-3.0-or-later"

[dependencies]

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
